### ISSUE TITLE
Request to go to the new edge browser extension store

### ISSUE THREAD

**Issue by ChirmyRam** [dashokkumar93/crx-download#1]
The new version of edge browser based on chrome kernel has been released. The extension can be put on the edge store free of charge. It is compatible with Chrome extension, and the number of users is increasing gradually.
So I hope that this extension can be put on the edge store to make it easier for more people to access this extension.And I hope it can extract the extensions of edge extension store in the same way.
Thank you very much.

**Comment by liudonghua123** [comment]
I found the edge add-on store has this extension already, see https://microsoftedge.microsoft.com/addons/detail/crx-extractordownloader/gfgehnhkaggeillajnpegcanbdjcbeja. The chrome version is on https://chrome.google.com/webstore/detail/ajkhmmldknmfjnmeedkbkkojgobmljda. I can't tell is it an official one.

But I tested both of them, they were not working as expected, both of them could not download crx/zip from the edge add-on store.

**Comment by ChirmyRam** [comment]
> I found the edge add-on store has this extension already, see https://microsoftedge.microsoft.com/addons/detail/crx-extractordownloader/gfgehnhkaggeillajnpegcanbdjcbeja. The chrome version is on https://chrome.google.com/webstore/detail/ajkhmmldknmfjnmeedkbkkojgobmljda. I can't tell is it an official one.
> 
> But I tested both of them, they were not working as expected, both of them could not download crx/zip from the edge add-on store.

确实有可能是别人盗的。Edge商店也没有Chrome商店那么开放。

**Comment by tonystark93** [comment]
@ChirmyRam The extension is released by me but under different name. I just love the tonystark name so i just used it to create the username with that name.

@liudonghua123 
 Just checked for the feasibility of downloading the Microsoft extension, it is possible. We will add it in upcoming update.

**Comment by ChirmyRam** [comment]
> @ChirmyRam The extension is released by me but under different name. I just love the tonystark name so i just used it to create the username under the name.
> 
> @liudonghua123
> Just checked for the feasibility of downloading the Microsoft extension, it is possible. We will add it in upcoming update.

Well, thank you very much. But at the moment I'm not responding to download extensions with it, and I'm looking forward to updates.

**Comment by win98se** [comment]
For now, power users can manually download CRX files from Edge Addons store by substituting `<<EXTENSION_ID>>` using the extension ID into the following URL - `https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&prod=chromiumcrx&prodchannel=&x=id%3D<<EXTENSION_ID>>%26installsource%3Dondemand%26uc`

Example, for https://microsoftedge.microsoft.com/addons/detail/pride-%E2%80%93-bisexual/jjamdofabacbjoobjmfppbamldncchmm, `jjamdofabacbjoobjmfppbamldncchmm` is the extension ID, so the CRX file URL is `https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&prod=chromiumcrx&prodchannel=&x=id%3Djjamdofabacbjoobjmfppbamldncchmm%26installsource%3Dondemand%26uc`.

**Comment by tonystark93** [comment]
@win98se  @liudonghua123 @ChirmyRam In the Latest [MR](https://github.com/tonystark93/crx-download/pull/8) the changes are available. Will publish the changes in a day or two
