### ISSUE TITLE
Migration to Manifest V3

### ISSUE THREAD

**Issue by bershanskiy** [dashokkumar93/crx-download#15]
Extension currently uses Manifest V2, which is deprecated and scheduled to be shut down next year. [Google says](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/) that in January 2023 "Chrome stops running Manifest V2 extensions" unless there is an "enterprise policy... within the organization." In June 2023, "Manifest V2 extensions [will] no longer function in Chrome even with the use of enterprise policy".

I can prepare a PR to migrate to MV3 if you are interested in reviewing it.

**Comment by bershanskiy** [comment]
For anyone interested, this [MV3 prototype](https://github.com/bershanskiy/webextension-downloader) works and allows you to download extensions from Chrome Web Store and Edge Addons store.

**Comment by tonystark93** [comment]
Hi @bershanskiy 
Thanks for the request. Recently tried to migrate to v3 version. The changes available in this [branch](https://github.com/tonystark93/crx-download/tree/manifest-v3-changes). 

There was an issue in the [chrome download as option](https://bugs.chromium.org/p/chromium/issues/detail?id=1246717#c13) Which has been fixed recently. We can check if this works fine in that version and make the changes.

**Comment by tonystark93** [comment]
Migrated to manifest v3
