### ISSUE TITLE
no "Download" options available anymore

### ISSUE THREAD

**Issue by jwmh** [dashokkumar93/crx-download#18]
I was using this extension yesterday (downloaded from Chrome Web / extensions store) and it worked fine

Today I downloaded it again
(i always boot up via netbootxyz so i have a fresh clean system each time)

and
it just says

"
Please go to Chrome Extension Store or Microsoft Addon Store and go to extension page to download chrome extensions.
Convert from CRX to ZIP file
"

I've tried clearing my chromium-browser cache etc

No fix.

This is the first time i've seen this issue occur.
P.S.
for clarification,
I'm at the URL:
https://chrome.google.com/webstore/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl
(Tabs Outliner)

I do this so I can use it in multiple Chromium profiles
(one for google, another for facebook, etc.)

...
and,
even after fully loading the webstore page,
this extension fails to recognize / provide an option to DOWNLOAD (either as zip or as crx) that extension.
.
The only option it offers now is to convert some existing, already-downloaded extension from crx to zip file.

**Comment by tonystark93** [comment]
Hi,
@jwmh Which version of CRX extractor you are using and what is the chrome/chromium, OS version you are using.

**Comment by QingLeiLi** [comment]
run into same issue.

CRX extractor: 1.5.6
Google Chrome: 107.0.5304.87
OS: macOS Monterey 12.0.1 (21A559)

**Comment by tonystark93** [comment]
@QingLeiLi 
Could you please share the extension url, to which you are facing the issue? 

Are you not able to download the extension using crx extractor popup?

If yes,
You could try right clicking on the extension page, and download the extension.
<img width="715" alt="image" src="https://user-images.githubusercontent.com/11315443/199880180-f115dde9-c083-4373-b32f-81118f997c98.png">

**Comment by QingLeiLi** [comment]
@tonystark93 noop.
There is no response after click `Download CRX for this extension` button.
Nothing happen.

**Comment by jwmh** [comment]
Same here, except I'm using Windows 10.
Chrome 108.0.5359.125 (Official Build) (64-bit)

**Comment by yadalik** [comment]
Same, Win 10, Chrome 108.0.5359.125, extension latest from today's chrome extensions site. It thinks, that not on extension page, agitating to go to google chrome extensions site, despite I already on this link:
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

When pressing RMB on page and selecting zip or crx download nothing happens.

**Comment by Francewhoa** [comment]
This is to confirm this challenge

The menu fails. Both CRX and ZIP. The button display "Please go to Chrome Extension Store or Microsoft Addon Store and go to extension page to download chrome extensions. Convert from CRX to ZIP file. Rate Us" Download buttons are not display. Thus, not clickable.

Using:
* CRX Extractor/Downloader 1.5.6
* Extension https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh
* Debian Buster 10
* [Ungoogle Chromium](https://github.com/ungoogled-software/ungoogled-chromium) 110.0.5481.100
* [chromium-web-store](https://github.com/NeverDecaf/chromium-web-store) 1.5.3

Both me and the Ubertus.org team would be happy to test a new version. Any volunteer for a patch?

**Comment by KaKi87** [comment]
Hello @tonystark93, any news on this ? Thanks

**Comment by tonystark93** [comment]
@KaKi87 Fixed some issues related to multiple window case where download option wont be available. Hope the new version 1.5.7 will get approved in a couple of days
