### ISSUE TITLE
Security Risk. Version between Github and Web Store do not match.

### ISSUE THREAD

**Issue by Francewhoa** [dashokkumar93/crx-download#19]
Steps to reproduce:

1.  As of February 18th, 2023, compare those two web page below. Notice that their versions do not match. 1.5.3 versus 1.56 

  1. According to this Github repository, the latest version of this extension is 1.5.3 at https://github.com/tonystark93/crx-download/releases/latest

     * https://archive.md/jjedL
     * https://archive.md/ITneM

  2. According to Web Store, the latest version of this extension is 1.5.6 at https://chrome.google.com/webstore/detail/crx-extractordownloader/ajkhmmldknmfjnmeedkbkkojgobmljda

     * https://archive.md/uCf4F

1. The challenge is that users are not able to review the code of the extension version 1.5.6. And contribute to it. In turn, this is a security risk. 

1. The needed end result is that both version match. Where the most important one is at https://github.com/tonystark93/crx-download/releases/latest

If needed, both me and the Ubertus.org team would be happy to test a new version. Any volunteer for a patch?

**Comment by tonystark93** [comment]
Updated the extension code
