### ISSUE TITLE
Crx-download doesn't work in microsoft edge store 

### ISSUE THREAD

**Issue by trimechee** [dashokkumar93/crx-download#7]
Hello, i have tried ti have the crx file of this this great video downloader  extension 
https://microsoftedge.microsoft.com/addons/detail/video-downloadhelper/jmkaglaafmhbcpleggkmaliipiilhldn

but Crx-downlad send just a pop up message to say to go to chrome store and rate the extension, it will be great if this problem will be fixed, thank you :)

**Comment by tonystark93** [comment]
In the Latest [MR](https://github.com/tonystark93/crx-download/pull/8) the changes are available. Will publish the changes in a day or two

**Comment by trimechee** [comment]
Great ! Thank you very much :)

Le sam. 18 sept. 2021 à 16:15, tonyStark93 ***@***.***> a
écrit :

**Comment by Philantrop** [comment]
A new release would now be highly desirable. :-)
